#!/bin/sh

# KETZ v1.05 - Kjell Emanuelsson 2023 - Time Zones - shell script exercise

color_check=$(tput colors)

if [ $color_check -gt 254 ]; then
    LOW="\033[38;5;110m"
    BLUE="\033[38;5;111m"
    GREEN="\033[38;5;115m"
    INVGREEN="\033[38;5;66m"
    INVLOW="\033[38;5;67m"
    INVBLUE="\033[38;5;67m"
elif [ $color_check -gt 15 ]; then
    LOW="\e[37m"
    BLUE="\e[94m"
    GREEN="\e[94m"
    INVGREEN="\e[34m"
    INVLOW="\e[90m"
    INVBLUE="\e[34m"
else
    LOW="\e[39m"
    BLUE="\e[39m"
    GREEN="\e[39m"
    INVGREEN="\e[39m"
    INVLOW="\e[39m"
    INVBLUE="\e[39m"
fi

date_f="%A %B %-d"
time_f="%R %Z"
unixtime=$(date +"%s")

column1="$GREEN%-14s $LOW%-13s %-18s $GREEN%-12s $BLUE%-6s\n"
column2="$INVGREEN%-14s $INVLOW%-13s %-18s $INVGREEN%-12s $INVBLUE%-6s\n"
localcol="\e[0m$INVLOW%-27s %-0s %-18s $BLUE%-14s\n"
extracol="\e[0m$INVLOW%-27s %-0s %-18s %-14s\n"

# FP for timezone offset calculation
fp_format() {
    if awk "BEGIN {exit !($1 == 0)}"
    then
        printf "LOCAL"
    elif awk "BEGIN {exit !($1 > 0)}"
    then
        printf "+%s"$1 | sed 's/\.0$//'
    else
        printf "%s"$1 | sed 's/\.0$//'
    fi
}

fp_trim_sub() {
    fp_format $(echo "$1 $2" | awk '{printf "%.1f", $1-$2}')
}

# "Quick" and dirty bash-floating point math(for mars clock)
# (all with awk-printf just because i didn't happen to have bc!)
fp_sub() {
    printf "$1 $2" | awk '{printf "%.16f", $1-$2}'
}

fp_div() {
    printf "$1 $2" | awk '{printf "%.16f", $1/$2}'
}

fp_add() {
    printf "$1 $2" | awk '{printf "%.16f", $1+$2}'
}

fp_mul() {
    printf "$1 $2" | awk '{printf "%.16f", $1*$2}'
}

fp_mod() {
    printf "$1 $2" | awk '{printf "%.16f", $1%$2}'
}

# Mars Clock (AM2000 implementation of James Tauber's marsclock.com
# (+also see NASA MSD notes https://www.giss.nasa.gov/tools/mars24/help/notes.html)
ms=$(fp_div $(date +"%s%N") 1000000)
jut=$(fp_add $(fp_div $ms 86400000) 2440587.5)
jls=$(fp_div $(fp_add 37 32.184) 86400)
jtt=$(fp_add $jut $jls)
j2k=$(fp_sub $jtt 2451545)
raw_msd=$(fp_sub $(fp_add $(fp_div $(fp_sub $j2k 4.5) 1.027491252) 44796) 0.00096)
mp=$(fp_mod $(fp_mul 24 $raw_msd) 24)
m_h=$(printf "%s\n"$mp | sed 's/\..*//')
min=$(fp_mod $(fp_mul 60 $mp) 60)
m_m=$(printf "%s\n"$min | sed 's/\..*//')
mtc=$(printf "%02d" $m_h)":"$(printf "%02d" $m_m)" MTC"
msd=$(LC_NUMERIC=C printf "MSD %.1f" $raw_msd)

# TIMEZONES
U="Coordinated Universal Time"
U_DATE=$(LC_TIME="en_GB.UTF-8" TZ="Universal" date +"$date_f")
U_TIME=$(LC_TIME="en_GB.UTF-8" TZ="Universal" date +"$time_f")

L="\e[1mLOCAL TIME\e[0m"
L_DATE=$(LC_TIME="en_US.UTF-8" date +"$date_f")
L_TIME=$(LC_TIME="en_US.UTF-8" date +"$time_f")
LTZ=$(timedatectl | grep "Time zone" | sed 's/\s*Time zone: //;' | sed 's/(.*//')
LTZ=${LTZ:0:28}
LO=$(date +"%-:::z")

R19A="Pago Pago"
R19B="Am.Samoa"
R19_DATE=$(LC_TIME="en_US.UTF-8" TZ="Pacific/Pago_Pago" date +"$date_f")
R19_TIME=$(LC_TIME="en_US.UTF-8" TZ="Pacific/Pago_Pago" date +"$time_f")
R19_TZ=$(fp_trim_sub -11 $LO)

R20A="Papeete"
R20B="Fr.Polynesia"
R20_DATE=$(LC_TIME="fr_PF.UTF-8" TZ="Pacific/Pago_Pago" date +"$date_f")
R20_TIME=$(LC_TIME="fr_PF.UTF-8" TZ="Pacific/Pago_Pago" date +"$time_f")
R20_TZ=$(fp_trim_sub -10 $LO)

R21A="Anchorage"
R21B="USA"
R21_DATE=$(LC_TIME="en_US.UTF-8" TZ="America/Anchorage" date +"$date_f")
R21_TIME=$(LC_TIME="en_US.UTF-8" TZ="America/Anchorage" date +"$time_f")
R21_TZ=$(fp_trim_sub -9 $LO)

R22A="Los Angeles"
R22B="USA"
R22_DATE=$(LC_TIME="en_US.UTF-8" TZ="America/Los_Angeles" date +"$date_f")
R22_TIME=$(LC_TIME="en_US.UTF-8" TZ="America/Los_Angeles" date +"$time_f")
R22_TZ=$(fp_trim_sub -8 $LO)

R23A="Edmonton"
R23B="Canada"
R23_DATE=$(LC_TIME="en_CA.UTF-8" TZ="America/Edmonton" date +"$date_f")
R23_TIME=$(LC_TIME="en_CA.UTF-8" TZ="America/Edmonton" date +"$time_f")
R23_TZ=$(fp_trim_sub -7 $LO)

R24A="Mexico City"
R24B="Mexico"
R24_DATE=$(LC_TIME="es_MX.UTF-8" TZ="America/Mexico_City" date +"$date_f")
R24_TIME=$(LC_TIME="es_MX.UTF-8" TZ="America/Mexico_City" date +"$time_f")
R24_TZ=$(fp_trim_sub -6 $LO)

R25A="New York"
R25B="USA"
R25_DATE=$(LC_TIME="en_US.UTF-8" TZ="America/New_York" date +"$date_f")
R25_TIME=$(LC_TIME="en_US.UTF-8" TZ="America/New_York" date +"$time_f")
R25_TZ=$(fp_trim_sub -5 $LO)

R26A="Caracas"
R26B="Venezuela"
R26_DATE=$(LC_TIME="es_VE.UTF-8" TZ="America/Caracas" date +"$date_f")
R26_TIME=$(LC_TIME="es_VE.UTF-8" TZ="America/Caracas" date +"$time_f")
R26_TZ=$(fp_trim_sub -4 $LO)

R2NA="St.John's"
R2NB="Canada"
R2N_DATE=$(LC_TIME="en_CA.UTF-8" TZ="America/St_Johns" date +"$date_f")
R2N_TIME=$(LC_TIME="en_CA.UTF-8" TZ="America/St_Johns" date +"$time_f")
R2N_TZ=$(fp_trim_sub -3.5 $LO)

R27A="Brasilia"
R27B="Brazil"
R27_DATE=$(LC_TIME="pt_BR.UTF-8" TZ="Brazil/East" date +"$date_f")
R27_TIME=$(LC_TIME="pt_BR.UTF-8" TZ="Brazil/East" date +"$time_f")
R27_TZ=$(fp_trim_sub -3 $LO)

R28A="South Georgia"
R28B="UK"
R28_DATE=$(LC_TIME="en_UK.UTF-8" TZ="Atlantic/South_Georgia" date +"$date_f")
R28_TIME=$(LC_TIME="en_UK.UTF-8" TZ="Atlantic/South_Georgia" date +"$time_f")
R28_TZ=$(fp_trim_sub -2 $LO)

R29A="Praia"
R29B="Cape Verde"
R29_DATE=$(LC_TIME="pt_CV.UTF-8" TZ="Atlantic/Cape_Verde" date +"$date_f")
R29_TIME=$(LC_TIME="pt_CV.UTF-8" TZ="Atlantic/Cape_Verde" date +"$time_f")
R29_TZ=$(fp_trim_sub -1 $LO)

R01A="Reykjavik"
R01B="Iceland"
R01_DATE=$(LC_TIME="is_IS.UTF-8" TZ="Iceland" date +"$date_f")
R01_TIME=$(LC_TIME="is_IS.UTF-8" TZ="Iceland" date +"$time_f")
R01_TZ=$(fp_trim_sub 0 $LO)

R02A="Yaounde"
R02B="Cameroon"
R02_DATE=$(LC_TIME="fr_CM.UTF-8" TZ="Africa/Douala" date +"$date_f")
R02_TIME=$(LC_TIME="fr_CM.UTF-8" TZ="Africa/Douala" date +"$time_f")
R02_TZ=$(fp_trim_sub 1 $LO)

R03A="Kyiv"
R03B="Ukraine"
R03_DATE=$(LC_TIME="uk_UA.UTF-8" TZ="Europe/Kyiv" date +"$date_f")
R03_TIME=$(LC_TIME="uk_UA.UTF-8" TZ="Europe/Kyiv" date +"$time_f")
R03_TZ=$(fp_trim_sub 2 $LO)

R04A="Antananarivo"
R04B="Madagasgar"
R04_DATE=$(LC_TIME="en_MG.UTF-8" TZ="Indian/Antananarivo" date +"$date_f")
R04_TIME=$(LC_TIME="en_MG.UTF-8" TZ="Indian/Antananarivo" date +"$time_f")
R04_TZ=$(fp_trim_sub 3 $LO)

R05A="Tehran"
R05B="Iran"
R05_DATE=$(LC_TIME="fa_IR.UTF-8" TZ="Iran" date +"$date_f")
R05_TIME=$(LC_TIME="fa_IR.UTF-8" TZ="Iran" date +"$time_f")
R05_TZ=$(fp_trim_sub 3.5 $LO)

R06A="Dubai"
R06B="UAE"
R06_DATE=$(LC_TIME="ar_AE.UTF-8" TZ="Asia/Dubai" date +"$date_f")
R06_TIME=$(LC_TIME="ar_AE.UTF-8" TZ="Asia/Dubai" date +"$time_f")
R06_TZ=$(fp_trim_sub 4 $LO)

R07A="Karachi"
R07B="Pakistan"
R07_DATE=$(LC_TIME="ur_PK.UTF-8" TZ="Asia/Karachi" date +"$date_f")
R07_TIME=$(LC_TIME="ur_PK.UTF-8" TZ="Asia/Karachi" date +"$time_f")
R07_TZ=$(fp_trim_sub 5 $LO)

R08A="New Delhi"
R08B="India"
R08_DATE=$(LC_TIME="en_IN.UTF-8" TZ="Asia/Kolkata" date +"$date_f")
R08_TIME=$(LC_TIME="en_IN.UTF-8" TZ="Asia/Kolkata" date +"$time_f")
R08_TZ=$(fp_trim_sub 5.5 $LO)

R09A="Astana"
R09B="Kazakhstan"
R09_DATE=$(LC_TIME="en_IN.UTF-8" TZ="Asia/Kolkata" date +"$date_f")
R09_TIME=$(LC_TIME="en_IN.UTF-8" TZ="Asia/Kolkata" date +"$time_f")
R09_TZ=$(fp_trim_sub 6 $LO)

R10A="Yangon"
R10B="Burma"
R10_DATE=$(LC_TIME="my_MM.UTF-8" TZ="Asia/Yangon" date +"$date_f")
R10_TIME=$(LC_TIME="my_MM.UTF-8" TZ="Asia/Yangon" date +"$time_f")
R10_TZ=$(fp_trim_sub 6.5 $LO)

R11A="Jakarta"
R11B="Indonesia"
R11_DATE=$(LC_TIME="id_ID.UTF-8" TZ="Asia/Jakarta" date +"$date_f")
R11_TIME=$(LC_TIME="id_ID.UTF-8" TZ="Asia/Jakarta" date +"$time_f")
R11_TZ=$(fp_trim_sub 7 $LO)

R12A="Taipei"
R12B="Taiwan"
R12_DATE=$(LC_TIME="zh_TW.UTF-8" TZ="Asia/Taipei" date +"$date_f")
R12_TIME=$(LC_TIME="zh_TW.UTF-8" TZ="Asia/Taipei" date +"$time_f")
R12_TZ=$(fp_trim_sub 8 $LO)

R13A="Tokyo"
R13B="Japan"
R13_DATE=$(LC_TIME="ja_JP.UTF-8" TZ="Japan" date +"$date_f")
R13_TIME=$(LC_TIME="ja_JP.UTF-8" TZ="Japan" date +"$time_f")
R13_TZ=$(fp_trim_sub 9 $LO)

R14A="Canberra"
R14B="Australia"
R14_DATE=$(LC_TIME="en_AU.UTF-8" TZ="Australia/Canberra" date +"$date_f")
R14_TIME=$(LC_TIME="en_AU.UTF-8" TZ="Australia/Canberra" date +"$time_f")
R14_TZ=$(fp_trim_sub 10 $LO)

R15A="Magadan"
R15B="Russia"
R15_DATE=$(LC_TIME="ru_RU.UTF-8" TZ="Asia/Magadan" date +"$date_f")
R15_TIME=$(LC_TIME="ru_RU.UTF-8" TZ="Asia/Magadan" date +"$time_f")
R15_TZ=$(fp_trim_sub 11 $LO)

R16A="Auckland"
R16B="New Zealand"
R16_DATE=$(LC_TIME="en_NZ.UTF-8" TZ="Pacific/Auckland" date +"$date_f")
R16_TIME=$(LC_TIME="en_NZ.UTF-8" TZ="Pacific/Auckland" date +"$time_f")
R16_TZ=$(fp_trim_sub 12 $LO)

R17A="Nuku'alofa"
R17B="Tonga"
R17_DATE=$(LC_TIME="en_TO.UTF-8" TZ="Pacific/Tongatapu" date +"$date_f")
R17_TIME=$(LC_TIME="en_TO.UTF-8" TZ="Pacific/Tongatapu" date +"$time_f")
R17_TZ=$(fp_trim_sub 13 $LO)

R18A="Line Islands"
R18B="Kiribati"
R18_DATE=$(LC_TIME="en_KI.UTF-8" TZ="Pacific/Kiritimati" date +"$date_f")
R18_TIME=$(LC_TIME="en_KI.UTF-8" TZ="Pacific/Kiritimati" date +"$time_f")
R18_TZ=$(fp_trim_sub 14 $LO)

echo
echo -e "$BLUE$L"
printf "$localcol" "$LTZ" "" "$L_DATE" "$L_TIME" "$L_PTZ"
printf "$column1" "$R19A" "$R19B" "$R19_DATE" "$R19_TIME" "$R19_TZ"
printf "$column2" "$R20A" "$R20B" "$R20_DATE" "$R20_TIME" "$R20_TZ"
printf "$column1" "$R21A" "$R21B" "$R21_DATE" "$R21_TIME" "$R21_TZ"
printf "$column2" "$R22A" "$R22A" "$R22_DATE" "$R22_TIME" "$R22_TZ"
printf "$column1" "$R23A" "$R23B" "$R23_DATE" "$R23_TIME" "$R23_TZ"
printf "$column2" "$R24A" "$R24B" "$R24_DATE" "$R24_TIME" "$R24_TZ"
printf "$column1" "$R25A" "$R25B" "$R25_DATE" "$R25_TIME" "$R25_TZ"
printf "$column2" "$R26A" "$R26B" "$R26_DATE" "$R26_TIME" "$R26_TZ"
printf "$column1" "$R2NA" "$R2NB" "$R2N_DATE" "$R2N_TIME" "$R2N_TZ"
printf "$column2" "$R27A" "$R27B" "$R27_DATE" "$R27_TIME" "$R27_TZ"
printf "$column1" "$R28A" "$R28B" "$R28_DATE" "$R28_TIME" "$R28_TZ"
printf "$column2" "$R29A" "$R29B" "$R29_DATE" "$R29_TIME" "$R29_TZ"
printf "$column1" "$R01A" "$R01B" "$R01_DATE" "$R01_TIME" "$R01_TZ"
printf "$column2" "$R02A" "$R02B" "$R02_DATE" "$R02_TIME" "$R02_TZ"
printf "$column1" "$R03A" "$R03B" "$R03_DATE" "$R03_TIME" "$R03_TZ"
printf "$column2" "$R04A" "$R04B" "$R04_DATE" "$R04_TIME" "$R04_TZ"
printf "$column1" "$R05A" "$R05B" "$R05_DATE" "$R05_TIME" "$R05_TZ"
printf "$column2" "$R06A" "$R06B" "$R06_DATE" "$R06_TIME" "$R06_TZ"
printf "$column1" "$R07A" "$R07B" "$R07_DATE" "$R07_TIME" "$R07_TZ"
printf "$column2" "$R08A" "$R08B" "$R08_DATE" "$R08_TIME" "$R08_TZ"
printf "$column1" "$R09A" "$R09B" "$R09_DATE" "$R09_TIME" "$R09_TZ"
printf "$column2" "$R10A" "$R10B" "$R10_DATE" "$R10_TIME" "$R10_TZ"
printf "$column1" "$R11A" "$R11B" "$R11_DATE" "$R11_TIME" "$R11_TZ"
printf "$column2" "$R12A" "$R12B" "$R12_DATE" "$R12_TIME" "$R12_TZ"
printf "$column1" "$R13A" "$R13B" "$R13_DATE" "$R13_TIME" "$R13_TZ"
printf "$column2" "$R14A" "$R14B" "$R14_DATE" "$R14_TIME" "$R14_TZ"
printf "$column1" "$R15A" "$R15B" "$R15_DATE" "$R15_TIME" "$R15_TZ"
printf "$column2" "$R16A" "$R16B" "$R16_DATE" "$R16_TIME" "$R16_TZ"
printf "$column1" "$R17A" "$R17B" "$R17_DATE" "$R17_TIME" "$R17_TZ"
printf "$column2" "$R18A" "$R18B" "$R18_DATE" "$R18_TIME" "$R18_TZ"
echo
printf "$extracol" "$U" "" "$U_DATE" "$U_TIME"
printf "$extracol" "Coordinated Mars Time" "" "$msd" "$mtc"
printf "$extracol" "Unix Time" "" "(Epoch)" "$unixtime"
echo
